name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  push_image:
    name: Push image
    runs-on: ubuntu-latest

    steps:
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: musikid/chwitter:latest,musikid/chwitter:${{ github.sha }},musikid/chwitter:${{ github.ref_name }}

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
